# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OptiDrape_DB_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptiDrape_DB_Interface(object):
    def setupUi(self, OptiDrape_DB_Interface):
        OptiDrape_DB_Interface.setObjectName("OptiDrape_DB_Interface")
        OptiDrape_DB_Interface.resize(547, 498)
        OptiDrape_DB_Interface.setMinimumSize(QtCore.QSize(547, 498))
        OptiDrape_DB_Interface.setMaximumSize(QtCore.QSize(547, 498))
        self.centralWidget = QtWidgets.QWidget(OptiDrape_DB_Interface)
        self.centralWidget.setObjectName("centralWidget")
        self.gbox_connection = QtWidgets.QGroupBox(self.centralWidget)
        self.gbox_connection.setGeometry(QtCore.QRect(10, 40, 531, 121))
        self.gbox_connection.setObjectName("gbox_connection")
        self.le_dburl_input = QtWidgets.QLineEdit(self.gbox_connection)
        self.le_dburl_input.setGeometry(QtCore.QRect(110, 30, 301, 21))
        self.le_dburl_input.setObjectName("le_dburl_input")
        self.dburl = QtWidgets.QLabel(self.gbox_connection)
        self.dburl.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.dburl.setObjectName("dburl")
        self.pB_connect_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_connect_db.setGeometry(QtCore.QRect(109, 60, 91, 22))
        self.pB_connect_db.setObjectName("pB_connect_db")
        self.pB_disconnect_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_disconnect_db.setGeometry(QtCore.QRect(310, 60, 101, 22))
        self.pB_disconnect_db.setObjectName("pB_disconnect_db")
        self.pB_load_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_load_db.setGeometry(QtCore.QRect(420, 30, 111, 22))
        self.pB_load_db.setObjectName("pB_load_db")
        self.cBox_databases = QtWidgets.QComboBox(self.gbox_connection)
        self.cBox_databases.setGeometry(QtCore.QRect(110, 90, 191, 22))
        self.cBox_databases.setObjectName("cBox_databases")
        self.cBox_databases.addItem("")
        self.dburl_2 = QtWidgets.QLabel(self.gbox_connection)
        self.dburl_2.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.dburl_2.setObjectName("dburl_2")
        self.pB_set_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_set_db.setGeometry(QtCore.QRect(310, 90, 101, 22))
        self.pB_set_db.setObjectName("pB_set_db")
        self.pB_refresh_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_refresh_db.setGeometry(QtCore.QRect(210, 60, 91, 21))
        self.pB_refresh_db.setObjectName("pB_refresh_db")
        self.pB_delete_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_delete_db.setGeometry(QtCore.QRect(420, 90, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_delete_db.setFont(font)
        self.pB_delete_db.setObjectName("pB_delete_db")
        self.pB_export_db = QtWidgets.QPushButton(self.gbox_connection)
        self.pB_export_db.setGeometry(QtCore.QRect(420, 60, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pB_export_db.setFont(font)
        self.pB_export_db.setObjectName("pB_export_db")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 521, 16))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gBox_viewer = QtWidgets.QGroupBox(self.centralWidget)
        self.gBox_viewer.setGeometry(QtCore.QRect(10, 170, 531, 301))
        self.gBox_viewer.setObjectName("gBox_viewer")
        self.tree_db_viewer = QtWidgets.QTreeView(self.gBox_viewer)
        self.tree_db_viewer.setGeometry(QtCore.QRect(0, 20, 191, 281))
        self.tree_db_viewer.setObjectName("tree_db_viewer")
        self.widget_db_viewer = QtWidgets.QWidget(self.gBox_viewer)
        self.widget_db_viewer.setGeometry(QtCore.QRect(200, 20, 331, 281))
        self.widget_db_viewer.setObjectName("widget_db_viewer")
        OptiDrape_DB_Interface.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(OptiDrape_DB_Interface)
        self.statusBar.setObjectName("statusBar")
        OptiDrape_DB_Interface.setStatusBar(self.statusBar)
        self.action_New_Project = QtWidgets.QAction(OptiDrape_DB_Interface)
        self.action_New_Project.setObjectName("action_New_Project")
        self.action_Load_Project = QtWidgets.QAction(OptiDrape_DB_Interface)
        self.action_Load_Project.setObjectName("action_Load_Project")
        self.action_Close_current_Project = QtWidgets.QAction(OptiDrape_DB_Interface)
        self.action_Close_current_Project.setObjectName("action_Close_current_Project")
        self.action_Exit = QtWidgets.QAction(OptiDrape_DB_Interface)
        self.action_Exit.setObjectName("action_Exit")
        self.actionSettings = QtWidgets.QAction(OptiDrape_DB_Interface)
        self.actionSettings.setObjectName("actionSettings")
        self.actionTools = QtWidgets.QAction(OptiDrape_DB_Interface)
        self.actionTools.setObjectName("actionTools")

        self.retranslateUi(OptiDrape_DB_Interface)
        QtCore.QMetaObject.connectSlotsByName(OptiDrape_DB_Interface)

    def retranslateUi(self, OptiDrape_DB_Interface):
        _translate = QtCore.QCoreApplication.translate
        OptiDrape_DB_Interface.setWindowTitle(_translate("OptiDrape_DB_Interface", "OptiDrape_DB_Interface"))
        self.gbox_connection.setTitle(_translate("OptiDrape_DB_Interface", "Connection"))
        self.le_dburl_input.setText(_translate("OptiDrape_DB_Interface", "http://localhost"))
        self.dburl.setText(_translate("OptiDrape_DB_Interface", "Database-URL:"))
        self.pB_connect_db.setText(_translate("OptiDrape_DB_Interface", "Connect"))
        self.pB_disconnect_db.setText(_translate("OptiDrape_DB_Interface", "Disconnect"))
        self.pB_load_db.setText(_translate("OptiDrape_DB_Interface", "Load Database"))
        self.cBox_databases.setItemText(0, _translate("OptiDrape_DB_Interface", "No Database"))
        self.dburl_2.setText(_translate("OptiDrape_DB_Interface", "Databases:"))
        self.pB_set_db.setText(_translate("OptiDrape_DB_Interface", "Set Database"))
        self.pB_refresh_db.setText(_translate("OptiDrape_DB_Interface", "Refresh"))
        self.pB_delete_db.setText(_translate("OptiDrape_DB_Interface", "Delete Database"))
        self.pB_export_db.setText(_translate("OptiDrape_DB_Interface", "Export Database"))
        self.label.setText(_translate("OptiDrape_DB_Interface", "OptiDrape - Database Manager"))
        self.gBox_viewer.setTitle(_translate("OptiDrape_DB_Interface", "Viewer"))
        self.action_New_Project.setText(_translate("OptiDrape_DB_Interface", "&New Project"))
        self.action_Load_Project.setText(_translate("OptiDrape_DB_Interface", "&Load Project"))
        self.action_Close_current_Project.setText(_translate("OptiDrape_DB_Interface", "&Close current Project"))
        self.action_Exit.setText(_translate("OptiDrape_DB_Interface", "&Exit"))
        self.actionSettings.setText(_translate("OptiDrape_DB_Interface", "Settings"))
        self.actionTools.setText(_translate("OptiDrape_DB_Interface", "Tools"))

