
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drapeparametermanager.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from gui.viewer.viewer_utils.rangeslider import *


class Ui_DrapeParameterManager(object):
    def setupUi(self, DrapeParameterManager):
        DrapeParameterManager.setObjectName("DrapeParameterManager")
        DrapeParameterManager.resize(745, 664)
        self.gridLayout_7 = QtWidgets.QGridLayout(DrapeParameterManager)
        self.gridLayout_7.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gBox_general = QtWidgets.QGroupBox(DrapeParameterManager)
        self.gBox_general.setMinimumSize(QtCore.QSize(291, 641))
        self.gBox_general.setObjectName("gBox_general")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gBox_general)
        self.gridLayout_8.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gBox_geo = QtWidgets.QGroupBox(self.gBox_general)
        self.gBox_geo.setObjectName("gBox_geo")
        self.gridLayout = QtWidgets.QGridLayout(self.gBox_geo)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_geo_name = QtWidgets.QLabel(self.gBox_geo)
        self.label_geo_name.setObjectName("label_geo_name")
        self.gridLayout.addWidget(self.label_geo_name, 0, 0, 1, 2)
        self.label_fitness_name = QtWidgets.QLabel(self.gBox_geo)
        self.label_fitness_name.setObjectName("label_model_name")
        self.gridLayout.addWidget(self.label_fitness_name, 1, 0, 1, 2)
        self.pB_geo_load = QtWidgets.QPushButton(self.gBox_geo)
        self.pB_geo_load.setMinimumSize(QtCore.QSize(111, 25))
        self.pB_geo_load.setMaximumSize(QtCore.QSize(150, 25))
        self.pB_geo_load.setObjectName("pB_geo_load")
        self.gridLayout.addWidget(self.pB_geo_load, 2, 0, 1, 1)
        self.pB_model_load = QtWidgets.QPushButton(self.gBox_geo)
        self.pB_model_load.setMinimumSize(QtCore.QSize(111, 25))
        self.pB_model_load.setMaximumSize(QtCore.QSize(150, 25))
        self.pB_model_load.setObjectName("pB_model_load")
        self.gridLayout.addWidget(self.pB_model_load, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.gBox_geo, 0, 0, 1, 1)
        self.gBox_textile = QtWidgets.QGroupBox(self.gBox_general)
        self.gBox_textile.setMinimumSize(QtCore.QSize(261, 351))
        self.gBox_textile.setObjectName("gBox_textile")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gBox_textile)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeView_textile = QtWidgets.QTreeView(self.gBox_textile)
        self.treeView_textile.setMinimumSize(QtCore.QSize(213, 156))
        self.treeView_textile.setObjectName("treeView_textile")
        self.gridLayout_2.addWidget(self.treeView_textile, 0, 0, 1, 2)
        self.pB_tex_load = QtWidgets.QPushButton(self.gBox_textile)
        self.pB_tex_load.setMinimumSize(QtCore.QSize(100, 25))
        self.pB_tex_load.setMaximumSize(QtCore.QSize(100, 25))
        self.pB_tex_load.setObjectName("pB_tex_load")
        self.gridLayout_2.addWidget(self.pB_tex_load, 1, 0, 1, 1)
        self.pB_tex_set = QtWidgets.QPushButton(self.gBox_textile)
        self.pB_tex_set.setMinimumSize(QtCore.QSize(101, 25))
        self.pB_tex_set.setMaximumSize(QtCore.QSize(101, 25))
        self.pB_tex_set.setObjectName("pB_tex_set")
        self.gridLayout_2.addWidget(self.pB_tex_set, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.gBox_textile, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gBox_general, 0, 0, 1, 1)
        self.gBox_constraints = QtWidgets.QGroupBox(DrapeParameterManager)
        self.gBox_constraints.setMinimumSize(QtCore.QSize(430, 646))
        self.gBox_constraints.setObjectName("gBox_constraints")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gBox_constraints)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gBox_global = QtWidgets.QGroupBox(self.gBox_constraints)
        self.gBox_global.setMinimumSize(QtCore.QSize(0, 204))
        self.gBox_global.setMaximumSize(QtCore.QSize(16777215, 204))
        self.gBox_global.setObjectName("gBox_global")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gBox_global)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_global = QtWidgets.QCheckBox(self.gBox_global)
        self.checkBox_global.setMinimumSize(QtCore.QSize(91, 23))
        self.checkBox_global.setMaximumSize(QtCore.QSize(91, 23))
        self.checkBox_global.setObjectName("checkBox_global")
        self.gridLayout_4.addWidget(self.checkBox_global, 0, 0, 1, 1)
        self.tabWidget_dim = QtWidgets.QTabWidget(self.gBox_global)
        self.tabWidget_dim.setMinimumSize(QtCore.QSize(381, 131))
        self.tabWidget_dim.setObjectName("tabWidget_dim")
        self.tab_point = QtWidgets.QWidget()
        self.tab_point.setObjectName("tab_point")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_point)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_x = QtWidgets.QLabel(self.tab_point)
        self.label_x.setMinimumSize(QtCore.QSize(51, 17))
        self.label_x.setMaximumSize(QtCore.QSize(51, 17))
        self.label_x.setObjectName("label_x")
        self.gridLayout_3.addWidget(self.label_x, 0, 0, 1, 1)
        self.hSlider_x = QRangeSlider(self.tab_point)
        #self.hSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_x.setObjectName("hSlider_x")
        self.gridLayout_3.addWidget(self.hSlider_x, 0, 1, 1, 1)

        self.label_y = QtWidgets.QLabel(self.tab_point)
        self.label_y.setMinimumSize(QtCore.QSize(51, 17))
        self.label_y.setMaximumSize(QtCore.QSize(51, 17))
        self.label_y.setObjectName("label_y")
        self.gridLayout_3.addWidget(self.label_y, 1, 0, 1, 1)

        self.hSlider_y = QRangeSlider(self.tab_point)
        #self.hSlider_y.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_y.setObjectName("hSlider_y")
        self.gridLayout_3.addWidget(self.hSlider_y, 1, 1, 1, 1)

        self.label_z = QtWidgets.QLabel(self.tab_point)
        self.label_z.setMinimumSize(QtCore.QSize(51, 17))
        self.label_z.setMaximumSize(QtCore.QSize(51, 17))
        self.label_z.setObjectName("label_z")
        self.gridLayout_3.addWidget(self.label_z, 2, 0, 1, 1)
        self.hSlider_z = QRangeSlider(self.tab_point)
        #self.hSlider_z.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider_z.setObjectName("hSlider_z")
        self.gridLayout_3.addWidget(self.hSlider_z, 2, 1, 1, 1)

        self.tabWidget_dim.addTab(self.tab_point, "")
        self.tab_global = QtWidgets.QWidget()

        gridLayout_tab_global = QtWidgets.QGridLayout(self.tab_global)
        gridLayout_tab_global.setContentsMargins(5, 5, 5, 5)
        gridLayout_tab_global.setSpacing(6)
        gridLayout_tab_global.setObjectName("gridLayout_tab_global")


        self.label_global_x_length = QtWidgets.QLabel(self.tab_global)
        self.label_global_x_length.setText("Length: %")
        self.label_global_x_length.setMinimumSize(QtCore.QSize(71, 17))
        self.label_global_x_length.setMaximumSize(QtCore.QSize(71, 17))
        self.label_global_x_length.setObjectName("label_global_xwidth")
        gridLayout_tab_global.addWidget(self.label_global_x_length, 0, 0, 1, 1)

        self.hSlider_global_x_length = QRangeSlider(self.tab_global)
        self.hSlider_global_x_length.setObjectName("hSlider_xwidth")
        gridLayout_tab_global.addWidget(self.hSlider_global_x_length, 0, 1, 1, 1)

        self.label_global_y_length = QtWidgets.QLabel(self.tab_global)
        self.label_global_y_length.setText("Width:  %")
        self.label_global_y_length.setMinimumSize(QtCore.QSize(71, 17))
        self.label_global_y_length.setMaximumSize(QtCore.QSize(71, 17))
        self.label_global_y_length.setObjectName("label_global_ywidth")
        gridLayout_tab_global.addWidget(self.label_global_y_length, 1, 0, 1, 1)

        self.hSlider_global_y_length = QRangeSlider(self.tab_global)
        self.hSlider_global_y_length.setObjectName("hSlider_ywidth")
        gridLayout_tab_global.addWidget(self.hSlider_global_y_length, 1, 1, 1, 1)

        self.label_global_z_length = QtWidgets.QLabel(self.tab_global)
        self.label_global_z_length.setText("Height: %")
        self.label_global_z_length.setMinimumSize(QtCore.QSize(71, 17))
        self.label_global_z_length.setMaximumSize(QtCore.QSize(71, 17))
        self.label_global_z_length.setObjectName("label_global_zwidth")
        gridLayout_tab_global.addWidget(self.label_global_z_length, 2, 0, 1, 1)

        self.hSlider_global_z_length = QRangeSlider(self.tab_global)
        self.hSlider_global_z_length.setObjectName("hSlider_zwidth")
        gridLayout_tab_global.addWidget(self.hSlider_global_z_length, 2, 1, 1, 1)



        self.tab_global.setObjectName("tab_global")
        self.tabWidget_dim.addTab(self.tab_global, "Global")



        self.gridLayout_4.addWidget(self.tabWidget_dim, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gBox_global, 0, 0, 1, 3)

        self.gBox_interaction = QtWidgets.QGroupBox(self.gBox_constraints)
        self.gBox_interaction.setObjectName("gBox_interaction")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gBox_interaction)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)

        self.widget_interaction = QtWidgets.QTabWidget(self.gBox_interaction)
        self.widget_interaction.setMinimumSize(QtCore.QSize(382, 286))
        self.widget_interaction.setObjectName("widget_interaction")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.widget_interaction.sizePolicy().hasHeightForWidth())
        self.widget_interaction.setSizePolicy(sizePolicy)

        self.gridLayout_5.addWidget(self.widget_interaction, 0, 0, 1, 4)

        self.gridLayout_6.addWidget(self.gBox_interaction, 1, 0, 1, 3)
        self.pB_clean = QtWidgets.QPushButton(self.gBox_constraints)
        self.pB_clean.setMinimumSize(QtCore.QSize(121, 25))
        self.pB_clean.setMaximumSize(QtCore.QSize(121, 25))
        self.pB_clean.setObjectName("pB_clean")
        self.gridLayout_6.addWidget(self.pB_clean, 2, 0, 1, 1)
        self.pB_set = QtWidgets.QPushButton(self.gBox_constraints)
        self.pB_set.setMinimumSize(QtCore.QSize(121, 25))
        self.pB_set.setMaximumSize(QtCore.QSize(121, 25))
        self.pB_set.setObjectName("pB_set")
        self.gridLayout_6.addWidget(self.pB_set, 2, 1, 1, 1)
        self.pB_save = QtWidgets.QPushButton(self.gBox_constraints)
        self.pB_save.setMinimumSize(QtCore.QSize(121, 25))
        self.pB_save.setMaximumSize(QtCore.QSize(121, 25))
        self.pB_save.setObjectName("pB_save")
        self.gridLayout_6.addWidget(self.pB_save, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.gBox_constraints, 0, 1, 1, 1)

        self.retranslateUi(DrapeParameterManager)
        self.tabWidget_dim.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DrapeParameterManager)

    def retranslateUi(self, DrapeParameterManager):
        _translate = QtCore.QCoreApplication.translate
        DrapeParameterManager.setWindowTitle(_translate("DrapeParameterManager", "DrapeParameterManager"))
        self.gBox_general.setTitle(_translate("DrapeParameterManager", "General:"))
        self.gBox_geo.setTitle(_translate("DrapeParameterManager", "Data:"))
        self.label_geo_name.setText(_translate("DrapeParameterManager", "No Geometry Loaded!"))
        self.label_fitness_name.setText(_translate("DrapeParameterManager", "No Fitness Model Loaded!"))
        self.pB_geo_load.setText(_translate("DrapeParameterManager", "Load Geometry"))
        self.pB_model_load.setText(_translate("DrapeParameterManager", "Load Fitness Model"))
        self.gBox_textile.setTitle(_translate("DrapeParameterManager", "Textile:"))
        self.pB_tex_load.setText(_translate("DrapeParameterManager", "Load Textile"))
        self.pB_tex_set.setText(_translate("DrapeParameterManager", "Set Textile"))
        self.gBox_constraints.setTitle(_translate("DrapeParameterManager", "Constraints:"))
        self.gBox_global.setTitle(_translate("DrapeParameterManager", "Global:"))
        self.checkBox_global.setText(_translate("DrapeParameterManager", "Activated"))
        self.label_x.setText(_translate("DrapeParameterManager", "x [mm]:"))
        self.label_y.setText(_translate("DrapeParameterManager", "y [mm]:"))
        self.label_z.setText(_translate("DrapeParameterManager", "z [mm]:"))
        self.tabWidget_dim.setTabText(self.tabWidget_dim.indexOf(self.tab_point), _translate("DrapeParameterManager", "Coordinates"))
        #self.tabWidget_dim.setTabText(self.tabWidget_dim.indexOf(self.tab_2), _translate("DrapeParameterManager", "Tab 2"))
        self.gBox_interaction.setTitle(_translate("DrapeParameterManager", "Interaction:"))
        #self.pB_interaction_new.setText(_translate("DrapeParameterManager", "New"))
        #self.pB_interaction_set.setText(_translate("DrapeParameterManager", "Set"))
        #self.pB_interaction_clean.setText(_translate("DrapeParameterManager", "Clean"))
        self.pB_set.setText(_translate("DrapeParameterManager", "Set Constraints"))
        self.pB_save.setText(_translate("DrapeParameterManager", "Save Constraints"))
        self.pB_clean.setText(_translate("DrapeParameterManager", "Clean All"))

